### PR TITLE
add node-fs-temporary

### PR DESCRIPTION
**Pull request by marijanp**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Hi @marijanp — the registry no longer accepts pull requests to add repositories to the new-packages.json and bower-packages.json registry files. Instead, please see:

https://github.com/purescript/registry#publish-a-package

However, I see you are using a non-GitHub package location. The registry is explicitly designed to support this, but during the registry alpha we do not support any locations except for GitHub. That's because the PureScript compiler's `publish` subcommand and, by extension, the [Pursuit](https://pursuit.purescript.org) packages website only accept packages from GitHub. We'll be lifting this restriction as soon as we can replace the `purs publish` process (there is an [issue tracking this on the registry-dev repo](https://github.com/purescript/registry-dev/issues/525)).

In the meantime, you can do one of:

* mirror your repository to GitHub, and register that location
* wait to register your repository until non-GitHub packages are supported

**Comment by marijanp** [comment]
@thomashoneyman my package requires a patched version of `node-os` because it's javascript syntax is deprecated. `node-os` also does not seem to be maintained anymore. Any suggestions on how to proceed?

I'm asking because creating the issue to add my package seems to require that it builds successfully.

**Comment by thomashoneyman** [comment]
All packages must compile to be registered. But you can choose what compiler to use — for example, if your project works with PureScript 0.14.0 you can publish it with that version.

Or am I misunderstanding you?

**Comment by thomashoneyman** [comment]
If the issue is that you are pointing to an unregistered dependency (your fork of node-os) then unfortunately your only option is to get that dependency updated and registered or to register your fork and point to that instead.

Packages in the registry can only depend on other packages in the registry.

Of course if you just need this for your application development then you can point at git links directly — your dependencies don’t all have to be registered

**Pull request closed without merging**
